In [1]:
import numpy as np

x_shape = (2, 3, 4, 4)
x = np.linspace(-0.3, 0.4, num=np.prod(x_shape)).reshape(x_shape)
pool_param = {'pool_width': 2, 'pool_height': 2, 'stride': 2}

out, _ = max_pool_forward_naive(x, pool_param)

correct_out = np.array([[[[-0.26315789, -0.24842105],
                          [-0.20421053, -0.18947368]],
                         [[-0.14526316, -0.13052632],
                          [-0.08631579, -0.07157895]],
                         [[-0.02736842, -0.01263158],
                          [ 0.03157895,  0.04631579]]],
                        [[[ 0.09052632,  0.10526316],
                          [ 0.14947368,  0.16421053]],
                         [[ 0.20842105,  0.22315789],
                          [ 0.26736842,  0.28210526]],
                         [[ 0.32631579,  0.34105263],
                          [ 0.38526316,  0.4       ]]]])


NameError: name 'max_pool_forward_naive' is not defined

In [12]:
x_slice = np.array(
[[[[ 6.,  1.],
   [ 3.,  2.]],

  [[ 2.,  8.],
   [ 9.,  4.]],

  [[ 5.,  3.],
   [ 6.,  9.]]],


 [[[ 7.,  4.],
   [ 6.,  3.]],

  [[ 9.,  8.],
   [ 1.,  4.]],

  [[ 3.,  9.],
   [ 7.,  3.]]]])
print "slice\n", x_slice

max_width = np.max(x_slice, axis=3)
args_width = np.argmax(x_slice, axis=3)
max_height = np.max(max_width, axis=2)
args_height = np.argmax(max_width, axis=2)

print "max_height", max_height

# this is for only one point...  We need stride across an image

# this confirm we can go back to coordinates
# NxCx2 for (row, col) per point and channel
max_idx = np.empty((2, 3, 2))
for p in range(2):
    for c in range(3):
        row = args_height[p, c]
        col = args_width[p, c, row]
        max_idx[p, c] = np.array([row, col])
# cache max_idx        
print "max_idx\n", max_idx


slice
[[[[ 6.  1.]
   [ 3.  2.]]

  [[ 2.  8.]
   [ 9.  4.]]

  [[ 5.  3.]
   [ 6.  9.]]]


 [[[ 7.  4.]
   [ 6.  3.]]

  [[ 9.  8.]
   [ 1.  4.]]

  [[ 3.  9.]
   [ 7.  3.]]]]
max_height [[ 6.  9.  9.]
 [ 7.  9.  9.]]
max_idx
[[[ 0.  0.]
  [ 1.  0.]
  [ 1.  1.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  1.]]]


In [10]:
H, W = 4, 8
HP, WP = 2, 2
S = 2
H_steps = (H - HP)/ S + 1
W_steps = (W - WP) / S + 1
print "H_steps, W_steps", H_steps, W_steps

for row in range(H_steps):
    for col in range(W_steps):
        print row * S, col * S
        
np.uint

H_steps, W_steps 2 4
0 0
0 2
0 4
0 6
2 0
2 2
2 4
2 6
