In [3]:
import numpy as np
from cs231n.gradient_check import eval_numerical_gradient, eval_numerical_gradient_array

# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

def rel_error(x, y):
  """ returns relative error """
  return np.max(np.abs(x - y) / (np.maximum(1e-8, np.abs(x) + np.abs(y))))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
W, H, D = (5, 5, 3)
K, F, S, P = (2, 3, 2, 1)
Win = W + 2 * P
Wout = (W -F + 2*P)/S + 1
print "out shape", (Wout, Wout, K)

x = np.zeros((Win, Win, D))
x[:, :, 0] = np.array([
    [0, 0, 0, 0, 0, 0, 0], 
    [0, 1, 2, 0, 2, 2, 0], 
    [0, 1, 2, 2, 0, 0, 0], 
    [0, 1, 0, 0, 2, 2, 0], 
    [0, 1, 1, 1, 1, 2, 0], 
    [0, 1, 0, 0, 1, 2, 0], 
    [0, 0, 0, 0, 0, 0, 0]
])

x[:, :, 1] = np.array([
    [0, 0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 1, 0, 1, 0], 
    [0, 0, 1, 1, 1, 0, 0], 
    [0, 0, 0, 0, 1, 1, 0], 
    [0, 2, 1, 0, 2, 1, 0], 
    [0, 1, 0, 0, 1, 1, 0], 
    [0, 0, 0, 0, 0, 0, 0]
])

x[:, :, 2]  = np.array([
    [0, 0, 0, 0, 0, 0, 0], 
    [0, 0, 2, 2, 2, 2, 0], 
    [0, 1, 0, 2, 2, 0, 0], 
    [0, 0, 1, 1, 0, 0, 0], 
    [0, 0, 2, 2, 2, 2, 0], 
    [0, 0, 0, 2, 0, 0, 0], 
    [0, 0, 0, 0, 0, 0, 0]
])

print "x.shape", x.shape

w0 = np.zeros((3, 3, 3))
w0[:, :, 0] = np.array([
        [1, -1, 0],
        [-1, 1, 0],
        [1, -1, 0]
    ])
w0[:, :, 1] = np.array([
        [0, 0, 0],
        [1, 1, -1],
        [-1, 0, 0]
    ])
w0[:, :, 2] = np.array([
        [0, -1, 0],
        [1, -1, -1],
        [1, -1, 0]
    ])
b0 = np.ones((1, 1, 1))

print "w0.shape, ", w0.shape
print "bo.shape", b0.shape

w1 = np.zeros((3, 3, 3))
w1[:, :, 0] = np.array([
        [1, 1, 0],
        [1, -1, -1],
        [0, 0, 0]
    ])
w1[:, :, 1] = np.array([
        [0, 1, 1],
        [1, 1, -1],
        [-1, 0, 1]
    ])
w1[:, :, 2] = np.array([
        [-1, 1, 1],
        [0, -1, 1],
        [0, -1, 0]
    ])
b1 = np.zeros((1, 1, 1))

V = np.zeros((Wout, Wout, K))

# first filter
# first row
V[0, 0, 0] = np.sum(x[0:3, 0:3, :] * w0) + b0
V[0, 1, 0] = np.sum(x[0:3, 2:5, :] * w0) + b0
V[0, 2, 0] = np.sum(x[0:3, 4:7, :] * w0) + b0
# second row
V[1, 0, 0] = np.sum(x[2:5, 0:3, :] * w0) + b0
V[1, 1, 0] = np.sum(x[2:5, 2:5, :] * w0) + b0
V[1, 2, 0] = np.sum(x[2:5, 4:7, :] * w0) + b0
# third row
V[2, 0, 0] = np.sum(x[4:7, 0:3, :] * w0) + b0
V[2, 1, 0] = np.sum(x[4:7, 2:5, :] * w0) + b0
V[2, 2, 0] = np.sum(x[4:7, 4:7, :] * w0) + b0


filters = (w0, w1)
bias = (b0, b1)
V = np.zeros((Wout, Wout, K))
for d in range(K):
    for i in range(Wout):
        for j in range(Wout):
            V[i, j, d] = np.sum(x[i*S:i*S+F, j*S:j*S+F, :] * filters[d]) + bias[d]
            
print V[:, :, 0]
print V[:, :, 1]
     

out shape (3, 3, 2)
x.shape (7, 7, 3)
w0.shape,  (3, 3, 3)
bo.shape (1, 1, 1)
[[-2. -5.  3.]
 [-2. -3.  0.]
 [ 2. -4.  1.]]
[[-1. -1. -2.]
 [ 4.  5. -4.]
 [ 6.  2.  5.]]


In [54]:
x = np.ones((2, 1, 3, 3))
print x.shape
pad = 1
x_pad = np.lib.pad(x, ((0, 0), (0, 0), (pad, pad), (pad, pad)), 'constant')
print x_pad.shape
print x[1, 0, :, :]
print x_pad[1, 0, :, :]

(2, 1, 3, 3)
(2, 1, 5, 5)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]


In [2]:
def forward(x, beta, gamma, eps):

    mean = np.mean(x)    
    x_minus_mean = x - mean
    squares = x_minus_mean ** 2
    var = np.mean(squares, axis=0)
    sqrt_var = np.sqrt(var + eps)
    one_over_sqrt_var = 1 / sqrt_var
    xhat = one_over_sqrt_var * x_minus_mean
    return gamma * xhat + beta

N, D = 3, 2
x = np.array(range(1, N*D+1), dtype="float64").reshape(N, D)
gamma = 3 * np.ones(D)
beta =  2 * np.ones(D)
eps = 1e-7

dout = np.ones_like(x)

print "x\n", x
print "beta\n", beta
print "gamma\n", gamma
print "forward\n", forward(x, beta, gamma, eps)

# evaluate numerical gradient
fx = lambda x: forward(x, beta, gamma, eps)
fbeta = lambda beta: forward(x, beta, gamma, eps)
fgamma = lambda gamma: forward(x, beta, gamma, eps)

h = 1e-3
dx_num = eval_numerical_gradient_array(fx, x, dout, h)
dbeta_num = eval_numerical_gradient_array(fbeta, beta, dout, h)
dgamma_num = eval_numerical_gradient_array(fgamma, gamma, dout, h)
print "dx_num\n", dx_num
print "dbeta_num\n", dbeta_num
print "dgamma_num\n", dgamma_num

# Evaluate gradient with forward and backprop and compare to
# numerical estimate

# forward pass as needed
mean = np.mean(x)    
x_minus_mean = x - mean
squares = x_minus_mean ** 2
var = np.mean(squares, axis=0)
sqrt_var = np.sqrt(var + eps)
one_over_sqrt_var = 1 / sqrt_var
xhat = one_over_sqrt_var * x_minus_mean
y = gamma * xhat + beta

# 9 + beta
dbeta = np.sum(dout, axis=0)
dgamma_xhat = dout

# 8 xhat * gamma
dgamma = np.sum(dgamma_xhat * xhat, axis=0)
dxhat = dgamma_xhat * gamma

# 7 x_minus_mean * one_over_sqrt_var
done_over_sqrt_var = np.sum(dxhat * x_minus_mean, axis=0)
dx_minus_mean_top = dxhat * one_over_sqrt_var

# 6 1/x
dsqrt_var = -(sqrt_var ** (-2)) * done_over_sqrt_var

#5 sqrt(var + eps)
dvar = 0.5 * ((var + eps)**(-0.5)) * dsqrt_var 

#4 np.mean
dsquares = (1.0 / N) * np.ones((N, D)) * dvar 

# 3 x**2
dx_minus_mean_bottom = 2.0 * x_minus_mean * dsquares

# 2 (x - mean)
# sum inbound gradient
dx_minus_mean = dx_minus_mean_top + dx_minus_mean_bottom 
# gradient to input node
dx_input = dx_minus_mean
# gradient to mean node
dmean = -np.sum(dx_minus_mean, axis=0)

#1 mean(x)
dx_mean = (1.0 / N) * np.ones((N, D)) * dmean

dx = dx_input + dx_mean

# compare
print "rel error dbeta", rel_error(dbeta, dbeta_num)
print "rel error dgamma", rel_error(dgamma, dgamma_num)
print "rel error dx", rel_error(dx, dx_num)
print dx_num
print dx

x
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
beta
[ 2.  2.]
gamma
[ 3.  3.]
forward
[[-2.39155025 -0.63493015]
 [ 1.12168995  2.87831005]
 [ 4.63493015  6.39155025]]
dx_num
[[ -6.02269702e-01   6.02269731e-01]
 [ -2.48533416e-08  -2.48552290e-08]
 [  6.02269731e-01  -6.02269702e-01]]
dbeta_num
[ 3.  3.]
dgamma_num
[-0.87831005  0.87831005]
rel error dbeta 1.2908193033e-13
rel error dgamma 1.10919908459e-13
rel error dx 1.0
[[ -6.02269702e-01   6.02269731e-01]
 [ -2.48533416e-08  -2.48552290e-08]
 [  6.02269731e-01  -6.02269702e-01]]
[[-0.60226973  0.60226973]
 [ 0.          0.        ]
 [ 0.60226973 -0.60226973]]
